# Assignment 3

In [2]:
import pandas as pd
import numpy as np

# Visualization
import plotly.express as px
import plotly.graph_objects as go

# Display options
pd.set_option("display.max_columns", None)

# Load data
df = pd.read_csv("netflix_titles.csv")

In [4]:
df = df.copy()

# Remove duplicate rows
df = df.drop_duplicates()

# Convert dates
# Remove leading/trailing whitespace first
df["date_added"] = df["date_added"].astype(str).str.strip()

# Convert to datetime
df["date_added"] = pd.to_datetime(
    df["date_added"],
    errors="coerce"
)
# Fill missing text values
text_columns = [
    "director",
    "cast",
    "country",
    "rating"
]

for col in text_columns:
    df[col] = df[col].fillna("Unknown")

# Drop rows missing genres
df = df.dropna(subset=["listed_in"])

# Create year/month columns
df["year_added"] = df["date_added"].dt.year
df["month_added"] = df["date_added"].dt.month_name()

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,September
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,September
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,September
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,September
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,September

In [9]:
# Extract duration number (e.g., 90 from "90 min" or 2 from "2 Seasons")
df["duration_number"] = (
    df["duration"]
    .str.extract(r"(\d+)")
    .astype(float)
)

df["duration_number"] = (
    df["duration"]
    .str.extract(r"(\d+)")
    .astype(float)
    .astype("Int64")  
)

# Simplify genres (keep only the first listed genre)
df["main_genre"] = (
    df["listed_in"]
    .str.split(",")
    .str[0]
    .str.strip()
)

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,duration_number,duration_type,main_genre
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,September,90,min,Documentaries
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,September,2,Seasons,International TV Shows
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,September,1,Season,Crime TV Shows
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,September,1,Season,Docuseries
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,September,2,Seasons,International TV Shows

In [10]:
df[["duration","duration_number","duration_type","main_genre"]].head(10)

    duration  duration_number duration_type                main_genre
0     90 min               90           min             Documentaries
1  2 Seasons                2       Seasons    International TV Shows
2   1 Season                1        Season            Crime TV Shows
3   1 Season                1        Season                Docuseries
4  2 Seasons                2       Seasons    International TV Shows
5   1 Season                1        Season                 TV Dramas
6     91 min               91           min  Children & Family Movies
7    125 min              125           min                    Dramas
8  9 Seasons                9       Seasons          British TV Shows
9    104 min              104           min                  Comedies